@startuml

class AbilityContextImpl

class AbilityContext

class ContextContainer

class app_Context

class Ability

class ContextImpl

class ablity_runtime_Context

AbilityContext <|-- AbilityContextImpl

ContextContainer <|-- AbilityContext

app_Context <|-- ContextContainer

app_Context <|-- ContextDeal

ablity_runtime_Context <|-- ContextImpl

AbilityContext <|-- Ability



@enduml