@startuml

class IFormMgr

class IRemoteBroker

class FormMgrProxy

class FormMgrStub

class FormMgrService

IRemoteBroker <|-- IFormMgr

IFormMgr <|-- FormMgrProxy

IFormMgr <|-- FormMgrStub

FormMgrStub <|-- FormMgrService

@enduml